import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="K-치킨 타이쿤 Master", layout="centered")

# 코드가 잘리지 않도록 아주 짧은 단위로 안전하게 나누었습니다.
html_lines = [
    "<!DOCTYPE html><html><head><meta charset='UTF-8'>",
    "<style>",
    "body { font-family: sans-serif; background-color: #1a1a24; text-align: center; padding: 5px; margin: 0; color: #ffffff; }",
    ".game-wrapper { background: #252632; padding: 12px; border-radius: 16px; border: 3px solid #3b3d54; display: inline-block; width: 330px; box-sizing: border-box; }",
    "h1 { color: #ffd43b; margin: 0; font-size: 20px; text-shadow: 2px 2px 0px #e67e22; }",
    ".sub-text { font-size: 10px; color: #a6a7b7; margin-bottom: 8px; }",
    ".game-screen { background-color: #f1f3f5; border: 3px solid #1a1a24; border-radius: 10px; height: 140px; margin: 8px 0; position: relative; overflow: hidden; }",
    ".kitchen-zone { position: absolute; left: 0; top: 0; width: 80px; height: 100%; background-color: #dee2e6; border-right: 3px dashed #495057; }",
    ".kitchen-title { font-size: 10px; color: #495057; font-weight: bold; margin-top: 3px; background: #ced4da; padding: 1px 0; }",
    ".hall-zone { position: absolute; right: 0; top: 0; width: 240px; height: 100%; background-color: #e9ecef; }",
    ".sprite { position: absolute; font-size: 26px; transition: transform 0.08s ease; }",
    ".chef { left: 20px; top: 35px; }",
    ".helper { left: 20px; top: 85px; display: none; }",
    ".table-seat { position: absolute; font-size: 22px; width: 40px; height: 40px; text-align: center; }",
    ".seat1 { right: 130px; top: 20px; }",
    ".seat2 { right: 30px; top: 20px; }",
    ".seat3 { right: 130px; top: 75px; }",
    ".seat4 { right: 30px; top: 75px; }",
    ".money-display { font-size: 22px; font-weight: bold; color: #51cf66; margin: 5px 0; text-shadow: 1px 1px 0px #2b8a3e; }",
    ".stats { font-size: 11px; color: #adc5dc; margin-bottom: 8px; background: #1c1c24; padding: 4px; border-radius: 6px; display: flex; justify-content: space-around; }",
    ".fry-btn { background-color: #f76707; color: white; border: none; padding: 10px; font-size: 15px; font-weight: bold; border-radius: 10px; cursor: pointer; border-bottom: 4px solid #d9480f; box-shadow: 0 3px #1a1a24; outline: none; width: 100%; box-sizing: border-box; }",
    ".fry-btn:active { border-bottom: 1px solid #d9480f; transform: translateY(3px); box-shadow: 0 1px #1a1a24; }",
    ".shop-section { margin-top: 12px; text-align: left; }",
    ".shop-title { font-size: 12px; color: #ffd43b; margin-bottom: 4px; font-weight: bold; }",
    ".upgrade-card { background: #1c1c24; padding: 6px 10px; margin: 4px 0; border-radius: 8px; display: flex; justify-content: space-between; align-items: center; border: 1px solid #3b3d54; }",
    ".upgrade-info { width: 65%; }",
    ".upgrade-name { font-weight: bold; color: #ffffff; font-size: 11px; }",
    ".upgrade-desc { color: #868e96; font-size: 9px; }",
    ".buy-btn { background-color: #37b24d; color: white; border: none; padding: 6px 10px; font-size: 11px; font-weight: bold; border-radius: 5px; cursor: pointer; }",
    ".buy-btn:disabled { background-color: #495057; color: #868e96; cursor: not-allowed; }",
    "@keyframes floatUp { 0% { transform: translateY(0); opacity: 1; } 100% { transform: translateY(-30px); opacity: 0; } }",
    ".floating-text { position: absolute; color: #40c057; font-weight: bold; font-size: 14px; animation: floatUp 0.6s ease-out forwards; pointer-events: none; z-index: 10; }",
    "</style></head>",
    "<body><div class='game-wrapper'><h1>🍗 타이쿤 마스터</h1><div class='sub-text'>레트로 도트 치킨 가게</div>",
    "<div class='game-screen' id='screen'><div class='kitchen-zone'><div class='kitchen-title'>주방</div><div class='sprite chef' id='chef-char'>👨‍🍳</div><div class='sprite helper' id='helper-char'>🧑‍🍳</div></div>",
    "<div class='hall-zone'><div class='table-seat seat1' id='s1'>🪑</div><div class='table-seat seat2' id='s2'>🪑</div><div class='table-seat seat3' id='s3'>🪑</div><div class='table-seat seat4' id='s4'>🪑</div></div></div>",
    "<div class='money-display'><span id='m'>0</span> ₩</div>",
    "<div class='stats'><div>🖱️ 클릭: <span id='pow'>1,000</span></div><div>⏰ 초당: <span id='auto'>0</span></div></div>",
    "<button class='fry-btn' onclick='fry()'>🍗 치킨 튀겨서 서빙하기!</button>",
    "<div class='shop-section'><div class='shop-title'>🛒 업그레이드 상점</div>",
    "<div class='upgrade-card'><div class='upgrade-info'><div class='upgrade-name'>🧑‍🍳 주방 알바 고용</div><div class='upgrade-desc'>자동 튀기기 (초당 +500)</div></div><button class='buy-btn' id='b1' onclick='buy(1)'><span id='c1'>10,000원</span></button></div>",
    "<div class='upgrade-card'><div class='upgrade-info'><div class='upgrade-name'>🌶️ 특제 소스 개발</div><div class='upgrade-desc'>단가 상승 (+1,500/클릭)</div></div><button class='buy-btn' id='b2' onclick='buy(2)'><span id='c2'>30,000원</span></button></div></div></div>",
    "<script>",
    "let money = 0; let power = 1000; let autoIncome = 0; let cost1 = 10000; let cost2 = 30000; let hasHelper = false;",
    "const guests = ['👨‍💼', '👩‍⚕️', '🐱', '🐶', '🦊', '👧'];",
    "function update() {",
    "document.getElementById('m').innerText = money.toLocaleString();",
    "document.getElementById('pow').innerText = power.toLocaleString();",
    "document.getElementById('auto').innerText = autoIncome.toLocaleString();",
    "document.getElementById('c1').innerText = cost1.toLocaleString() + '원';",
    "document.getElementById('c2').innerText = cost2.toLocaleString() + '원';",
    "document.getElementById('b1').disabled = (money < cost1);",
    "document.getElementById('b2').disabled = (money < cost2);",
    "if(hasHelper) { document.getElementById('helper-char').style.display = 'block'; }",
    "}",
    "function fry() {",
    "  money += power;",
    "  const chef = document.getElementById('chef-char');",
    "  chef.style.transform = 'scale(1.2) translateY(-5px)';",
    "  setTimeout(function() { chef.style.transform = 'scale(1) translateY(0)'; }, 80);",
    "  createFloatingText();",
    "  update();",
    "}",
    "function createFloatingText() {",
    "  const screen = document.getElementById('screen');",
    "  const text = document.createElement('div');",
    "  text.className = 'floating-text';",
    "  text.innerText = '+' + power.toLocaleString() + '원';",
    "  text.style.left = (15 + Math.random() * 15) + 'px';",
    "  text.style.top = (30 + Math.random() * 15) + 'px';",
    "  screen.appendChild(text);",
    "  setTimeout(function() { text.remove(); }, 600);",
    "}",
    "function buy(type) {",
    "  if(type === 1 && money >= cost1) {",
    "    money -= cost1; autoIncome += 500; cost1 = Math.floor(cost1 * 1.5); hasHelper = true;",
    "  } else if(type === 2 && money >= cost2) {",
    "    money -= cost2; power += 1500; cost2 = Math.floor(cost2 * 1.6);",
    "  }",
    "  update();",
    "}",
    "setInterval(function() {",
    "  for(let i=1; i<=4; i++) {",
    "    const seat = document.getElementById('s' + i);",
    "    if(Math.random() > 0.45) {",
    "      const idx = Math.floor(Math.random() * guests.length);",
    "      seat.innerText = guests[idx] + '🍗';",
    "    } else { seat.innerText = '🪑'; }",
    "  }",
    "}, 1800);",
    "setInterval(function() { if(autoIncome > 0) { money += autoIncome; update(); } }, 1000);",
    "update();",
    "</script></body></html>"
]

full_html = "".join(html_lines)
components.html(full_html, height=480)
