import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(
    page_title="K-치킨 요리 타이쿤", 
    layout="centered"
)

# 그래픽 요소를 대폭 강화한 HTML/CSS 세팅
h = "<!DOCTYPE html><html><head><meta charset='UTF-8'>"
h += "<style>"
h += "body { font-family: sans-serif; "
h += "background-color: #1a1a24; "
h += "text-align: center; padding: 5px; "
h += "margin: 0; color: #ffffff; "
h += "user-select: none; }"
h += ".game-wrapper { background: #252632; "
h += "padding: 12px; border-radius: 16px; "
h += "border: 3px solid #3b3d54; "
h += "display: inline-block; width: 350px; "
h += "box-sizing: border-box; }"
h += "h1 { color: #ffd43b; margin: 0; "
h += "font-size: 20px; "
h += "text-shadow: 2px 2px 0px #e67e22; }"
h += ".money-display { font-size: 26px; "
h += "font-weight: bold; color: #51cf66; "
h += "margin: 6px 0; "
h += "text-shadow: 1px 1px 0px #2b8a3e; }"

# 🍳 그래픽 주방 보드 디자인
h += ".kitchen-board { "
h += "background-color: #495057; "
h += "border: 4px solid #1a1a24; "
h += "border-radius: 12px; padding: 10px; "
h += "margin: 10px 0; display: flex; "
h += "justify-content: space-between; "
h += "box-shadow: inset 0 0 10px #000; }"

h += ".zone { background: #343a40; "
h += "border: 2px solid #6c757d; "
h += "border-radius: 8px; width: 95px; "
h += "height: 120px; display: flex; "
h += "flex-direction: column; "
h += "align-items: center; "
h += "justify-content: center; "
h += "position: relative; cursor: pointer; "
h += "box-shadow: 0 4px #1a1a24; }"
h += ".zone:active { transform: translateY(2px); "
h += "box-shadow: 0 2px #1a1a24; }"

h += ".zone-title { font-size: 11px; "
h += "font-weight: bold; color: #ffffff; "
h += "margin-bottom: 5px; "
h += "background: #212529; width: 100%; "
h += "position: absolute; top: 0; "
h += "border-top-left-radius: 5px; "
h += "border-top-right-radius: 5px; "
h += "padding: 2px 0; text-align: center; }"

# 🍗 CSS로 직접 그린 치킨 그래픽 오브젝트
h += ".graphic-item { width: 50px; height: 50px; "
h += "border-radius: 50%; position: relative; "
h += "margin-top: 15px; display: flex; "
h += "align-items: center; justify-content: center; "
h += "font-weight: bold; font-size: 10px; "
h += "text-shadow: 1px 1px 0 #000; }"

# 각 조리 상태별 비주얼 디자인
h += ".status-none { background: transparent; "
h += "border: 2px dashed #6c757d; color: #6c757d; "
h += "border-radius: 8px; width: 45px; height: 45px; }"
h += ".status-raw { background: #ffc9c9; "
h += "border: 3px solid #fa5252; color: #c92a2a; "
h += "border-radius: 40% 60% 60% 40%; "
h += "box-shadow: inset -5px -5px 0 #f03e3e; }"
h += ".status-battered { background: #fff4e6; "
h += "border: 3px solid #ffe8cc; color: #d9480f; "
h += "border-radius: 50% 40% 50% 40%; "
h += "box-shadow: inset -5px -5px 0 #ffd8a8; }"
h += ".status-frying { background: #fab005; "
h += "border: 3px solid #f59f00; color: #fff; "
h += "border-radius: 50%; "
h += "animation: boil 0.2s infinite alternate; "
h += "box-shadow: 0 0 12px #f59f00; }"
h += ".status-cooked { background: #e8590c; "
h += "border: 3px solid #d9480f; color: #fff; "
h += "border-radius: 30% 60% 70% 40%; "
h += "box-shadow: inset -6px -6px 0 #bc5100, 0 3px 5px rgba(0,0,0,0.3); }"

# 🫧 보글보글 끓는 애니메이션 효과
h += "@keyframes boil { "
h += "  0% { transform: scale(1) rotate(0deg); }"
h += "  100% { transform: scale(1.08) rotate(3deg); }"
h += "}"

# ⏳ 게이지바 스타일
h += ".progress-bar { width: 85%; "
h += "background-color: #212529; "
h += "height: 10px; border-radius: 5px; "
h += "overflow: hidden; margin-top: 8px; "
h += "border: 1px solid #6c757d; }"
h += ".progress-fill { height: 100%; "
h += "width: 0%; background: linear-gradient(to right, #f59f00, #f76707); "
h += "transition: width 0.1s linear; }"

# ⚙️ 기타 하단 버튼 및 레이아웃
h += ".serve-btn { "
h += "background: linear-gradient(to bottom, #40c057, #2b8a3e); "
h += "color: white; border: none; "
h += "padding: 12px; font-size: 16px; "
h += "font-weight: bold; box-shadow: 0 4px #1e5e2a; "
h += "border-radius: 10px; cursor: pointer; "
h += "width: 100%; box-sizing: border-box; "
h += "margin-bottom: 10px; }"
h += ".serve-btn:active { transform: translateY(3px); "
h += "box-shadow: 0 1px #1e5e2a; }"
h += ".serve-btn:disabled { background: #5c636a; "
h += "box-shadow: none; cursor: not-allowed; "
h += "transform: none; color: #969faf; }"
h += ".status-msg { font-size: 13px; "
h += "color: #ffd43b; min-height: 20px; "
h += "margin-bottom: 6px; font-weight: bold; "
h += "background: #1c1c24; padding: 4px; "
h += "border-radius: 6px; }"
h += ".shop-section { background: #1c1c24; "
h += "padding: 10px; border-radius: 8px; "
h += "text-align: left; "
h += "border: 1px solid #3b3d54; }"
h += ".shop-title { font-size: 12px; "
h += "color: #ffd43b; font-weight: bold; "
h += "margin-bottom: 4px; }"
h += ".upgrade-text { font-size: 11px; "
h += "color: #adc5dc; display: flex; "
h += "justify-content: space-between; "
h += "align-items: center; }"
h += ".buy-btn { "
h += "background: linear-gradient(to bottom, #ff922b, #f56a00); "
h += "color: white; border: none; "
h += "padding: 6px 10px; font-size: 11px; "
h += "font-weight: bold; "
h += "border-radius: 5px; cursor: pointer; "
h += "box-shadow: 0 2px #b84d00; }"
h += ".buy-btn:active { transform: translateY(1px); box-shadow: none; }"
h += ".buy-btn:disabled { background: #495057; color: #868e96; "
h += "box-shadow: none; cursor: not-allowed; }"
h += "</style></head>"

# 🏪 본문 그래픽 레이아웃 구성
h += "<body><div class='game-wrapper'>"
h += "<h1>🍳 K-치킨 타이쿤</h1>"
h += "<div class='money-display'>"
h += "<span id='money'>0</span> ₩</div>"
h += "<div class='status-msg' id='msg'>"
h += "준비대의 생닭을 클릭해 반죽을 입히세요!</div>"
h += "<div class='kitchen-board'>"

# 1단계: 준비대 (생닭 블록 무대)
h += "<div class='zone' onclick='clickPrep()'>"
h += "<div class='zone-title'>1. 준비대</div>"
h += "<div id='p-item' class='graphic-item status-raw'>RAW</div>"
h += "</div>"

# 2단계: 튀김기 (기름 끓는 이펙트 무대)
h += "<div class='zone' onclick='clickFry()'>"
h += "<div class='zone-title'>2. 튀김기</div>"
h += "<div id='f-item' class='graphic-item status-none'>EMPTY</div>"
h += "<div class='progress-bar'>"
h += "<div class='progress-fill' id='bar'></div>"
h += "</div>"
h += "</div>"

# 3단계: 가판대 접시 무대
h += "<div class='zone'>"
h += "<div class='zone-title'>3. 완성 도마</div>"
h += "<div id='pl-item' class='graphic-item status-none'>EMPTY</div>"
h += "</div>"
h += "</div>"

# 버튼 및 하단 기능 업그레이드
h += "<button class='serve-btn' id='serve' "
h += "onclick='serveChicken()' disabled>"
h += "🥡 바삭한 치킨 손님에게 서빙하기"
h += "</button>"
h += "<div class='shop-section'>"
h += "<div class='shop-title'>⚙️ 주방 설비 업그레이드</div>"
h += "<div class='upgrade-text'>"
h += "<span>🔥 고화력 가스 레인지 (튀김속도 업)</span>"
h += "<button class='buy-btn' id='up-btn' "
h += "onclick='upgradeFry()'>"
h += "<span id='cost'>3,000</span>원"
h += "</button>"
h += "</div></div></div>"

# 🕹️ 게임 구동 핵심 자바스크립트 엔진
h += "<script>"
h += "let money = 0;"
h += "let chickenState = 'raw';"
h += "let fryProgress = 0;"
h += "let fryInterval = null;"
h += "let frySpeed = 5;"
h += "let upgradeCost = 3000;"
h += "let chickenPrice = 2500;"

h += "function msg(t) { "
h += "document.getElementById('msg').innerText = t; "
h += "}"

h += "function updateUI() {"
h += "  document.getElementById('money').innerText = money.toLocaleString();"
h += "  document.getElementById('cost').innerText = upgradeCost.toLocaleString();"
h += "  document.getElementById('up-btn').disabled = (money < upgradeCost);"
h += "  document.getElementById('serve').disabled = (chickenState !== 'plate');"
h += "}"

h += "function clickPrep() {"
h += "  if (chickenState === 'raw') {"
h += "    chickenState = 'battered';"
h += "    let p = document.getElementById('p-item');"
h += "    p.className = 'graphic-item status-battered';"
h += "    p.innerText = 'MIX';"
h += "    msg('반죽물 옷을 입혔습니다! 튀김기로 보내세요.');"
h += "  }"
h += "}"

h += "function clickFry() {"
h += "  if (chickenState === 'battered') {"
h += "    chickenState = 'frying';"
h += "    document.getElementById('p-item').className = 'graphic-item status-none';"
h += "    document.getElementById('p-item').innerText = 'EMPTY';"
h += "    let f = document.getElementById('f-item');"
h += "    f.className = 'graphic-item status-frying';"
h += "    f.innerText = 'FRY';"
h += "    msg('기름 속에서 보글보글 튀겨지는 중...');"
h += "    fryProgress = 0;"
h += "    fryInterval = setInterval(function() {"
h += "      fryProgress += frySpeed;"
h += "      if (fryProgress > 100) { fryProgress = 100; }"
h += "      document.getElementById('bar').style.width = fryProgress + '%';"
h += "      if (fryProgress >= 100) {"
h += "        clearInterval(fryInterval);"
h += "        chickenState = 'cooked';"
h += "        document.getElementById('f-item').innerText = 'READY';"
h += "        msg('황금빛 노릇한 치킨 완성! 클릭하여 건져내세요.');"
h += "      }"
h += "    }, 100);"
h += "  } else if (chickenState === 'cooked') {"
h += "    chickenState = 'plate';"
h += "    let f = document.getElementById('f-item');"
h += "    f.className = 'graphic-item status-none';"
h += "    f.innerText = 'EMPTY';"
h += "    document.getElementById('bar').style.width = '0%';"
h += "    let pl = document.getElementById('pl-item');"
h += "    pl.className = 'graphic-item status-cooked';"
h += "    pl.innerText = 'CHICKEN';"
h += "    msg('포장 완료! 서빙 버튼을 눌러 서빙하세요.');"
h += "    updateUI();"
h += "  }"
h += "}"

h += "function serveChicken() {"
h += "  if (chickenState === 'plate') {"
h += "    money += chickenPrice;"
h += "    chickenState = 'raw';"
h += "    let pl = document.getElementById('pl-item');"
h += "    pl.className = 'graphic-item status-none';"
h += "    pl.innerText = 'EMPTY';"
h += "    let p = document.getElementById('p-item');"
h += "    p.className = 'graphic-item status-raw';"
h += "    p.innerText = 'RAW';"
h += "    msg('치킨 배달 판매 성공! (+ ' + chickenPrice.toLocaleString() + '원)');"
h += "    updateUI();"
h += "  }"
h += "}"

h += "function upgradeFry() {"
h += "  if (money >= upgradeCost) {"
h += "    money -= upgradeCost;"
h += "    frySpeed += 4;"
h += "    chickenPrice += 1200;"
h += "    upgradeCost = Math.floor(upgradeCost * 2.3);"
h += "    msg('화력 증강 완료! 조리 속도와 판매 단가가 올랐습니다!');"
h += "    updateUI();"
h += "  }"
h += "}"

h += "updateUI();"
h += "</script></body></html>"

components.html(h, height=450)
