import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(
    page_title="K-치킨 리얼 튀김기", 
    layout="centered"
)

# 잘림 현상을 원천 차단하기 위해 모든 코드를 극단적으로 쪼갭니다.
code = "<!DOCTYPE html><html><head><meta charset='UTF-8'>"
code += "<style>"
code += "body { font-family: sans-serif; "
code += "background: #111219; color: #fff; "
code += "text-align: center; margin: 0; "
code += "padding: 5px; user-select: none; }"
code += ".pad { background: #222533; padding: 12px; "
code += "border-radius: 16px; border: 4px solid #f39c12; "
code += "display: inline-block; width: 340px; "
code += "box-sizing: border-box; }"
code += "h1 { color: #f1c40f; margin: 0 0 5px 0; "
code += "font-size: 18px; "
code += "text-shadow: 2px 2px 0px #d35400; }"
code += ".status-panel { background: #151722; "
code += "padding: 8px; border-radius: 8px; "
code += "font-size: 14px; font-weight: bold; "
code += "color: #2ecc71; margin-bottom: 10px; "
code += "display: flex; "
code += "justify-content: space-between; }"

# 🔥 리얼 튀김기 그래픽 화면 디자인
code += ".fryer-pot { background: #34495e; "
code += "border: 4px solid #2c3e50; "
code += "border-radius: 12px; height: 130px; "
code += "position: relative; overflow: hidden; "
code += "margin-bottom: 10px; "
code += "box-shadow: inset 0 0 20px #000; }"
code += ".oil-layer { position: absolute; bottom: 0; "
code += "width: 100%; height: 75%; "
code += "background: #f1c40f; opacity: 0.8; "
code += "transition: background 0.3s; }"
code += ".boil-active { "
code += "animation: wave 0.1s infinite alternate; "
code += "background: #e67e22 !important; }"
code += "@keyframes wave { "
code += "  0% { transform: translateY(0); }"
code += "  100% { transform: translateY(2px); }"
code += "}"

# 🍗 튀김기 내부의 치킨 그래픽 상태
code += ".chicken-obj { width: 60px; height: 60px; "
code += "border-radius: 40% 60% 50% 40%; "
code += "position: absolute; left: 135px; top: 45px; "
code += "display: flex; align-items: center; "
code += "justify-content: center; font-size: 10px; "
code += "font-weight: bold; color: #fff; "
code += "text-shadow: 1px 1px 1px #000; "
code += "transition: all 0.2s; }"
code += ".c-raw { background: #ffb3b3; "
code += "border: 2px solid #ff4d4d; }"
code += ".c-fry { background: #f39c12; "
code += "border: 2px solid #d35400; "
code += "animation: spin 0.5s infinite alternate; }"
code += ".c-crispy { background: #964b00; "
code += "border: 2px solid #592e00; }"
code += ".c-burnt { background: #222; "
code += "border: 2px solid #000; color: #777; }"
code += "@keyframes spin { "
code += "  0% { transform: rotate(0deg); }"
h = "  100% { transform: rotate(3deg) scale(1.05); }"
code += h + "}"

# 📊 상태 표시 및 컨트롤러 패널
code += ".gauge-box { background: #151722; "
code += "padding: 6px; border-radius: 6px; "
code += "margin-bottom: 8px; font-size: 11px; "
code += "text-align: left; }"
code += ".bar-bg { background: #333; height: 10px; "
code += "border-radius: 5px; overflow: hidden; "
code += "margin: 2px 0 6px 0; }"
code += ".bar-fill { height: 100%; width: 0%; "
code += "background: #2ecc71; }"
code += ".btn-group { display: flex; gap: 6px; "
code += "margin-bottom: 6px; }"
code += ".ctrl-btn { flex: 1; background: #3498db; "
code += "color: #fff; border: none; padding: 10px; "
code += "font-weight: bold; font-size: 12px; "
code += "border-radius: 6px; cursor: pointer; "
code += "border-bottom: 3px solid #2980b9; }"
code += ".ctrl-btn:active { transform: translateY(2px); "
code += "border-bottom: 1px solid #2980b9; }"
code += ".btn-fire { background: #e74c3c; "
code += "border-bottom: 3px solid #c0392b; }"
code += ".btn-serve { background: #2ecc71; "
code += "border-bottom: 3px solid #27ae60; "
code += "width: 100%; padding: 12px; "
code += "font-size: 14px; margin-top: 4px; }"
code += ".btn-serve:disabled { background: #555; "
code += "border: none; cursor: not-allowed; }"
code += "</style></head>"

# 🏪 본문 게임 인터페이스 드로잉
code += "<body><div class='pad'>"
code += "<h1>👨‍🍳 리얼 크리스피 튀김기</h1>"
code += "<div class='status-panel'>"
code += "<div>보유 금액: <span id='m'>0</span>원</div>"
code += "<div>품질 점수: <span id='q'>-</span></div>"
code += "</div>"

# 리얼 튀김기 창탱크 구역
code += "<div class='fryer-pot'>"
code += "<div class='oil-layer' id='oil'></div>"
code += "<div class='chicken-obj c-raw' id='chicken'>대기중</div>"
code += "</div>"

# 유저 실시간 조작 게이지 시스템
code += "<div class='gauge-box'>"
code += "<span>🌡️ 기름 온도 (<span id='txt-temp'>140</span>°C) - [목표: 170~190°C]</span>"
code += "<div class='bar-bg'><div class='bar-fill' id='b-temp' style='width:40%; background:#3498db;'></div></div>"
code += "<span>🍗 익은 정도 (튀김 진척도)</span>"
code += "<div class='bar-bg'><div class='bar-fill' id='b-cook' style='width:0%; background:#f1c40f;'></div></div>"
code += "</div>"

# 조작 물리 버튼 크래프트
code += "<div class='btn-group'>"
code += "<button class='ctrl-btn btn-fire' onmousedown='heat(true)' onmouseup='heat(false)' onmouseleave='heat(false)'>🔥 불조절 (누르고 있기)</button>"
code += "<button class='ctrl-btn' onclick='flip()'>🔄 치킨 뒤집기</button>"
code += "</div>"
code += "<button class='ctrl-btn btn-serve' id='serve' onclick='serve()' disabled>🛎️ 건져내서 손님상에 서빙</button>"
code += "</div>"

# 🕹️ 고성능 튀김 시뮬레이터 물리 엔진 스크립트
code += "<script>"
code += "let money = 0; let temp = 140; let cook = 0;"
code += "let isHeating = false; let chickenState = 'raw'; " # raw -> frying -> cooked -> burnt
code += "let flipCount = 0; let quality = '없음';"

code += "function heat(val) { isHeating = val; }"

# 실시간 물리 연산 코어 루프 (0.1초마다 가동)
code += "setInterval(function() {"
code += "  if (isHeating) { temp += 4.5; } else { temp -= 1.8; }"
code += "  if (temp < 100) temp = 100; if (temp > 250) temp = 250;"
code += "  let tPct = ((temp - 100) / 150) * 100;"
code += "  let barT = document.getElementById('b-temp');"
code += "  barT.style.width = tPct + '%';"
code += "  document.getElementById('txt-temp').innerText = Math.floor(temp);"
code += "  if (temp >= 170 && temp <= 190) { barT.style.background = '#2ecc71'; } "
code += "  else if (temp > 190) { barT.style.background = '#e74c3c'; } "
code += "  else { barT.style.background = '#3498db'; }"
code += "  let oil = document.getElementById('oil');"
code += "  if (temp > 160) { oil.className = 'oil-layer boil-active'; } "
code += "  else { oil.className = 'oil-layer'; }"

# 치킨 조리 가속 및 상태 머신 연산
code += "  if (chickenState === 'frying') {"
code += "    if (temp >= 170 && temp <= 190) { cook += 1.8; } "
code += "    else if (temp > 190) { cook += 3.5; } "
code += "    else if (temp >= 140) { cook += 0.5; }"
code += "    if (cook > 100) cook = 100;"
code += "    document.getElementById('b-cook').style.width = cook + '%';"
code += "    let c = document.getElementById('chicken');"
code += "    if (cook >= 40 && cook < 85) { c.innerText = '튀겨지는중'; }"
code += "    if (cook >= 85 && cook < 100) {"
code += "      chickenState = 'cooked'; c.className = 'chicken-obj c-crispy';"
code += "      c.innerText = '황금바삭'; document.getElementById('serve').disabled = false;"
code += "    }"
code += "  } else if (chickenState === 'cooked') {"
code += "    if (temp > 160) cook += 1.2;"
code += "    if (cook >= 100) {"
code += "      chickenState = 'burnt'; let c = document.getElementById('chicken');"
code += "      c.className = 'chicken-obj c-burnt'; c.innerText = '숯둥이';"
code += "    }"
code += "  }"
code += "}, 100);"

# 튀김 액션 함수들
code += "function flip() {"
code += "  if (chickenState === 'raw') {"
code += "    chickenState = 'frying'; let c = document.getElementById('chicken');"
code += "    c.className = 'chicken-obj c-fry'; c.innerText = '지글지글';"
code += "  } else if (chickenState === 'frying' || chickenState === 'cooked') {"
code += "    flipCount++; let c = document.getElementById('chicken');"
code += "    c.style.transform = 'scaleY(-1)'; "
code += "    setTimeout(function(){ c.style.transform = 'scaleY(1)'; }, 150);"
code += "  }"
code += "}"

code += "function serve() {"
code += "  if (chickenState === 'cooked') {"
code += "    let pay = 3000;"
code += "    if (flipCount >= 2 && flipCount <= 4) { quality = '명품 ⭐️'; pay += 1500; } "
code += "    else if (flipCount > 4) { quality = '조금 산만함'; } "
code += "    else { quality = '덜 뒤집음'; pay -= 500; }"
code += "    money += pay; document.getElementById('q').innerText = quality;"
code += "  } else if (chickenState === 'burnt') {"
code += "    document.getElementById('q').innerText = '폐기처리'; money -= 1000;"
code += "  }"
code += "  chickenState = 'raw'; cook = 0; flipCount = 0;"
code += "  let c = document.getElementById('chicken');"
code += "  c.className = 'chicken-obj c-raw'; c.innerText = '대기중';"
code += "  document.getElementById('b-cook').style.width = '0%';"
code += "  document.getElementById('serve').disabled = true;"
code += "  document.getElementById('m').innerText = money.toLocaleString();"
code += "}"
code += "</script></body></html>"

components.html(code, height=450)
